# 101 NumPy

In [8]:
import numpy as np 
num = 1_000_000
list_np = np.arange(num)
list_py = list(range(num))

In [9]:
# Cuanto tiempo se demora en multiplicar una list
%timeit list_time = [x * 2 for x in list_py]

57.7 ms ± 1.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
# Cuanto tiempo se demora en multiplicar un arreglo en np
%timeit list_np*2

1.35 ms ± 64.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
# Arreglo simple
arreglo = np.array([[1,2,3],[3,4,5]])
arreglo *11 + arreglo

array([[12, 24, 36],
       [36, 48, 60]])

In [21]:
# arreglo.shape # Output (2,3)
arreglo.dtype # Output dtype('int64')
arreglo.ndim  # Output 2 

2

In [32]:
# Np Zero and Ones
arreglo_zero_1 = np.zeros(33)
arreglo_zero_2 = np.zeros((4,4))
arreglo_unos_1 = np.ones(11)
arreglo_unos_2 = np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [35]:
# Np empty
arreglo_vacio = np.empty((3,4,5))
arreglo_vacio

array([[[4.79173844e-310, 0.00000000e+000, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310]],

       [[6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310]],

       [[6.50893702e-310, 6.50893702e-310, 6.50893702e-310,
         6.50893702e-310, 6.50893702e-310],
        [6.50893702e-310, 6.50893702e-310, 6.50893702e-310,


In [37]:
# arange
arreglo_a = np.arange(22)
arreglo_a.dtype

dtype('int64')

In [42]:
# eye
arreglo_eye = np.eye(3,)
arreglo_eye[0]

array([1., 0., 0.])